import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Form from '../pcomponents/Form'
import Todo from '../pcomponents/Todo'
import Button from '../pcomponents/Button'
import Keypad from '../pcomponents/Keypad'
import Transition from '../pcomponents/Transition'
import TodoFun from '../pcomponents/TodoFun'
import ElizaBot from '../pcomponents/Eliza'
import Gallery from '../pcomponents/Gallery'
import Links from '../pcomponents/Links'
import SafeQuestion from '../pcomponents/SafeQuestion'
import AlertButton from '../pcomponents/AlertButton'

import AlertButtonRaw from '../pcomponentsraw/AlertButtonRaw'
import ButtonRaw from '../pcomponentsraw/ButtonRaw'
import ElizaBotRaw from '../pcomponentsraw/ElizaRaw'
import FormRaw from '../pcomponentsraw/FormRaw'
import GalleryRaw from '../pcomponentsraw/GalleryRaw'
import KeypadRaw from '../pcomponentsraw/KeypadRaw'
import LinksRaw from '../pcomponentsraw/LinksRaw'
import SafeQuestionRaw from '../pcomponentsraw/SafeQuestionRaw'
import TodoFunRaw from '../pcomponentsraw/TodoFunRaw'
import TodoRaw from '../pcomponentsraw/TodoRaw'
import TransitionRaw from '../pcomponentsraw/TransitionRaw'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="storyApp">
        <div className="wholeWidth" ><Form /></div>  
        <div className="wholeWidth" ><AlertButton/></div>
        <div className="wholeWidth" ><Button/></div>  
        <div className="wholeWidth" ><Todo/></div>  
        <div className="wholeWidth" ><TodoFun/></div>  
        <div className="wholeWidth" ><Links/></div>  
        <div className="wholeWidth" ><Transition/></div>  
        <div className="wholeWidth" ><Gallery/></div>  
        <div className="wholeWidth" ><ElizaBot/></div>  
        <div className="bottom">
        <div className="bottomLeft" ><Keypad/></div>  
        <div className="bottomRight" ><SafeQuestion/></div>
        </div>

       
        {/* 
        <div className="wholeWidth" ><FormRaw /></div>  
        <div className="wholeWidth" ><AlertButtonRaw/></div>
        <div className="wholeWidth" ><ButtonRaw/></div>  
        <div className="wholeWidth" ><TodoRaw/></div>  
        <div className="wholeWidth" ><TodoFunRaw/></div>  
        <div className="wholeWidth" ><LinksRaw/></div>  
        <div className="wholeWidth" ><TransitionRaw/></div>  
        <div className="wholeWidth" ><GalleryRaw/></div>  
        <div className="wholeWidth" ><ElizaBotRaw/></div>  
        <div className="wholeWidth" ><KeypadRaw/></div>  
        <div className="wholeWidth" ><SafeQuestionRaw/></div> */}

      </main>

     
      <footer className={styles.footer}>

        </footer>
    </div>
  )
}
